"""This is generated by gemini. I didn't change anything here except selecting the features."""
import streamlit as st
import pandas as pd
from joblib import load

# Load trained model
# Make sure this path is correct!
try:
    model = load("models/student_performance.joblib")
except FileNotFoundError:
    st.error("Error: Model file 'models/student_performance.joblib' not found.")
    st.stop()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()


st.title("Student Performance Prediction")
st.write("Predict whether a student will pass or fail based on 15 key attributes.")
st.set_page_config(page_title="Student Performance Prediction", layout="wide")


# remove the 3 dots
st.markdown("""
    <style>
        .reportview-container {
            margin-top: -2em;
        }
        #MainMenu {visibility: hidden;}
        .stDeployButton {display:none;}
        footer {visibility: hidden;}
        #stDecoration {display:none;}
    </style>
""", unsafe_allow_html=True)
st.markdown(
    r"""
    <style>
    .stDeployButton {
            visibility: hidden;
        }
    </style>
    """, unsafe_allow_html=True
)

# Input fields for features
st.sidebar.header("Student Information")

def get_user_input():
    # --- Sliders for Numeric Data ---
    # I've used your descriptions to set the min, max, and a reasonable default.
    failures = st.sidebar.slider("Past class failures", 0, 4, 0)
    absences = st.sidebar.slider("Number of school absences", 0, 93, 3)
    goout = st.sidebar.slider("Going out with friends (1=Low, 5=High)", 1, 5, 3)
    freetime = st.sidebar.slider("Free time after school (1=Low, 5=High)", 1, 5, 3)
    Medu = st.sidebar.slider("Mother's education (0=None, 4=Higher Ed)", 0, 4, 2)
    age = st.sidebar.slider("Student's age", 15, 22, 16)
    health = st.sidebar.slider("Current health status (1=Bad, 5=Good)", 1, 5, 3)
    traveltime = st.sidebar.slider("Travel time (1=<15m, 4=>1h)", 1, 4, 1)

    # --- Selectboxes for Categorical/Binary Data ---
    # We get user-friendly strings...
    internet_str = st.sidebar.selectbox("Internet access at home", ["No", "Yes"])
    schoolsup_str = st.sidebar.selectbox("Extra educational support", ["No", "Yes"])
    paid_str = st.sidebar.selectbox("Extra paid classes", ["No", "Yes"])
    famsize_str = st.sidebar.selectbox("Family size", ["Less than or equal to 3", "Greater than 3"])
    Mjob_str = st.sidebar.selectbox("Mother's job", ["Teacher", "Health", "Services", "At Home", "Other"])
    guardian_str = st.sidebar.selectbox("Guardian", ["Mother", "Father", "Other"])
    Pstatus_str = st.sidebar.selectbox("Parent's cohabitation status", ["Living Together", "Apart"])
    
    # --- Mappings ---
    # ...then we convert them to the numbers the model expects.
    # **ATTENTION!** These mappings (e.g., "No": 0, "Yes": 1) are an ASSUMPTION.
    # They MUST match exactly how you preprocessed your data before training!
    
    internet = 1 if internet_str == "Yes" else 0
    schoolsup = 1 if schoolsup_str == "Yes" else 0
    paid = 1 if paid_str == "Yes" else 0
    
    # Assuming 'LE3' was 0 and 'GT3' was 1
    famsize = 1 if famsize_str == "Greater than 3" else 0 
    
    # Assuming 'T' (Together) was 0 and 'A' (Apart) was 1
    Pstatus = 1 if Pstatus_str == "Apart" else 0
    
    # Assuming these were label-encoded in this order.
    mjob_map = {"Teacher": 0, "Health": 1, "Services": 2, "At Home": 3, "Other": 4}
    guardian_map = {"Mother": 0, "Father": 1, "Other": 2}

    Mjob = mjob_map[Mjob_str]
    guardian = guardian_map[guardian_str]

    # Build the data dictionary with the correct feature names
    data = {
        'failures': failures,
        'absences': absences,
        'goout': goout,
        'freetime': freetime,
        'internet': internet,
        'schoolsup': schoolsup,
        'paid': paid,
        'Medu': Medu,
        'age': age,
        'famsize': famsize,
        'Mjob': Mjob,
        'guardian': guardian,
        'health': health,
        'traveltime': traveltime,
        'Pstatus': Pstatus
    }
    
    # Create the DataFrame
    # It's also good practice to ensure the column order is *exactly*
    # what the model was trained on, just in case.
    feature_order = [
        'failures', 'absences', 'goout', 'freetime', 'internet', 'schoolsup',
        'paid', 'Medu', 'age', 'famsize', 'Mjob', 'guardian', 'health',
        'traveltime', 'Pstatus'
    ]
    
    features = pd.DataFrame([data], columns=feature_order)
    return features

input_df = get_user_input()

# --- Prediction ---
# This part of your code was fine.
prediction = model.predict(input_df)[0]
prediction_proba = model.predict_proba(input_df)[0]

st.subheader("Prediction")
# Display the result with a nice big icon
if prediction == 1:
    st.markdown("## ✅ Pass")
else:
    st.markdown("## ❌ Fail")

st.subheader("Prediction Probabilities")
st.write(f"Likelihood to Pass: {prediction_proba[1]*100:.2f}%")
st.write(f"Likelihood to Fail: {prediction_proba[0]*100:.2f}%")

# This is for your own debugging - it's good to see what's being sent
st.subheader("Input Features Sent to Model")
st.dataframe(input_df)
